name: reusable_workflow

on:
  workflow_call:
    inputs:
      input_1:
        required: true
        type: string
        default: "input_1_defult"
      input_2:
        required: false
        type: number
        default: 1
      input_3:
        required: false
        type: boolean
        default: true


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Print Input
        run: echo "${{ inputs.input_1 }}"
